services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models/ollama:/root/.ollama
      - ./temp-files:/tmp/temp-files
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    ports:
      - 11434:11434